---
galaxy_info:
  role_name: genesis
  namespace: opscores
  author: opscores
  description: Create new blockchain with genesis validator
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
        - "26.04"
    - name: Debian
      versions:
        - "13"
  galaxy_tags:
    - genesis
    - blockchain
    - cosmos
    - tendermint
    - validator
  dependencies:
    - role: opscores.umesh_net.common
    - role: opscores.umesh_net.preflight