namespace: opscores
name: umesh_net
version: 1.0.0
readme: README.md
authors:
  - Alexey Gorynovich
description: Ansible collection for deploying Umesh blockchain node topology (Validator + Sentry + RPC)
license:
  - MIT
tags:
  - blockchain
  - tendermint
  - cosmos
  - umesh
  - validator
  - sentry
  - rpc
dependencies: {}
repository: https://github.com/opscores/opscores.umesh_net
documentation: https://github.com/opscores/opscores.umesh_net
homepage: https://github.com/opscores/opscores.umesh_net
issues: https://github.com/opscores/opscores.umesh_net/issues
build_ignore:
  - '*.tar.gz'