---
# Deploy Validator node
# Joins an existing blockchain

- name: Deploy Validator
  hosts: validator
  become: true
  gather_facts: true

  vars:
    sentinel_ip: ""
    join_genesis_url: ""
    persistent_peers_for_join: ""

  roles:
    - role: opscores.umesh_net.validator